In [17]:
from src.html import html
html(1, "DSC 550 Data Mining", "Dong Woon Kim<br>Bellevue University Masters in Data Science<br>DSC 550 Data Mining<br>Discussion/Participation")

HTML(value='\n    <div align="center">\n    <h1 style="font-variant:smallcaps; font-family:Times New Roman;">D…

**1** Create a list of PyPi modules to install, save as requirements.txt, and install the modules.

In [143]:
# Create a list of PyPi modules to install
requirements = [
    "jupytext",
    "statistics",
    "pandas",
    "numpy",
    "ipywidgets",
    "IPython"
]

# Save as requirements.txt
requirements = "\n".join(requirements)
with open("./requirements.txt", "w") as f:
    f.write(requirements)

# Install the PyPi modules
%pip install -r requirements.txt

Requirement already satisfied: jupytext in C:\Users\Danny\python\.venv\Lib\site-packages (from -r requirements.txt (line 1)) (1.19.3)
Requirement already satisfied: statistics in C:\Users\Danny\python\.venv\Lib\site-packages (from -r requirements.txt (line 2)) (1.0.3.5)
Requirement already satisfied: pandas in C:\Users\Danny\python\.venv\Lib\site-packages (from -r requirements.txt (line 3)) (3.0.3)
Requirement already satisfied: numpy in C:\Users\Danny\python\.venv\Lib\site-packages (from -r requirements.txt (line 4)) (2.4.6)
Requirement already satisfied: ipywidgets in C:\Users\Danny\python\.venv\Lib\site-packages (from -r requirements.txt (line 5)) (8.1.8)
Requirement already satisfied: IPython in C:\Users\Danny\python\.venv\Lib\site-packages (from -r requirements.txt (line 6)) (9.14.1)
Requirement already satisfied: markdown-it-py>=1.0 in C:\Users\Danny\python\.venv\Lib\site-packages (from jupytext->-r requirements.txt (line 1)) (4.2.0)
Requirement already satisfied: mdit-py-plugins in C:\Users\Danny\python\.venv\Lib\site-packages (from jupytext->-r requirements.txt (line 1)) (0.6.1)
Requirement already satisfied: nbformat in C:\Users\Danny\python\.venv\Lib\site-packages (from jupytext->-r requirements.txt (line 1)) (5.10.4)
Requirement already satisfied: packaging in C:\Users\Danny\python\.venv\Lib\site-packages (from jupytext->-r requirements.txt (line 1)) (26.2)
Requirement already satisfied: pyyaml in C:\Users\Danny\python\.venv\Lib\site-packages (from jupytext->-r requirements.txt (line 1)) (6.0.3)
Requirement already satisfied: docutils>=0.3 in C:\Users\Danny\python\.venv\Lib\site-packages (from statistics->-r requirements.txt (line 2)) (0.23)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Danny\python\.venv\Lib\site-packages (from pandas->-r requirements.txt (line 3)) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Danny\python\.venv\Lib\site-packages (from pandas->-r requirements.txt (line 3)) (2026.2)
Requirement already satisfied: comm>=0.1.3 in C:\Users\Danny\python\.venv\Lib\site-packages (from ipywidgets->-r requirements.txt (line 5)) (0.2.3)
Requirement already satisfied: traitlets>=4.3.1 in C:\Users\Danny\python\.venv\Lib\site-packages (from ipywidgets->-r requirements.txt (line 5)) (5.15.1)
Requirement already satisfied: widgetsnbextension~=4.0.14 in C:\Users\Danny\python\.venv\Lib\site-packages (from ipywidgets->-r requirements.txt (line 5)) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in C:\Users\Danny\python\.venv\Lib\site-packages (from ipywidgets->-r requirements.txt (line 5)) (3.0.16)
Requirement already satisfied: colorama>=0.4.4 in C:\Users\Danny\python\.venv\Lib\site-packages (from IPython->-r requirements.txt (line 6)) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in C:\Users\Danny\python\.venv\Lib\site-packages (from IPython->-r requirements.txt (line 6)) (5.3.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in C:\Users\Danny\python\.venv\Lib\site-packages (from IPython->-r requirements.txt (line 6)) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in C:\Users\Danny\python\.venv\Lib\site-packages (from IPython->-r requirements.txt (line 6)) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.6 in C:\Users\Danny\python\.venv\Lib\site-packages (from IPython->-r requirements.txt (line 6)) (0.2.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\Users\Danny\python\.venv\Lib\site-packages (from IPython->-r requirements.txt (line 6)) (3.0.52)
Requirement already satisfied: psutil>=7 in C:\Users\Danny\python\.venv\Lib\site-packages (from IPython->-r requirements.txt (line 6)) (7.2.2)
Requirement already satisfied: pygments>=2.14.0 in C:\Users\Danny\python\.venv\Lib\site-packages (from IPython->-r requirements.txt (line 6)) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in C:\Users\Danny\python\.venv\Lib\site-packages (from IPython->-r requirements.txt (line 6)) (0.6.3)
Requirement already satisfied: wcwidth in C:\Users\Danny\python\.venv\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->IPython->-r requirements.txt (line 6)) (0.8.0)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in C:\Users\Danny\python\.venv\Lib\site-packages (from jedi>=0.18.2->IPython->-r requirements.txt (line 6)) (0.8.7)
Requirement already satisfied: mdurl~=0.1 in C:\Users\Danny\python\.venv\Lib\site-packages (from markdown-it-py>=1.0->jupytext->-r requirements.txt (line 1)) (0.1.2)
Requirement already satisfied: six>=1.5 in C:\Users\Danny\python\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 3)) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in C:\Users\Danny\python\.venv\Lib\site-packages (from stack_data>=0.6.0->IPython->-r requirements.txt (line 6)) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in C:\Users\Danny\python\.venv\Lib\site-packages (from stack_data>=0.6.0->IPython->-r requirements.txt (line 6)) (3.0.1)
Requirement already satisfied: pure-eval in C:\Users\Danny\python\.venv\Lib\site-packages (from stack_data>=0.6.0->IPython->-r requirements.txt (line 6)) (0.2.3)
Requirement already satisfied: fastjsonschema>=2.15 in C:\Users\Danny\python\.venv\Lib\site-packages (from nbformat->jupytext->-r requirements.txt (line 1)) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in C:\Users\Danny\python\.venv\Lib\site-packages (from nbformat->jupytext->-r requirements.txt (line 1)) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in C:\Users\Danny\python\.venv\Lib\site-packages (from nbformat->jupytext->-r requirements.txt (line 1)) (5.9.1)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\Danny\python\.venv\Lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->-r requirements.txt (line 1)) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\Danny\python\.venv\Lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->-r requirements.txt (line 1)) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\Danny\python\.venv\Lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->-r requirements.txt (line 1)) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in C:\Users\Danny\python\.venv\Lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->-r requirements.txt (line 1)) (2026.5.1)
Requirement already satisfied: platformdirs>=2.5 in C:\Users\Danny\python\.venv\Lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->-r requirements.txt (line 1)) (4.10.0)
Note: you may need to restart the kernel to use updated packages.

In [8]:
html(1, "Week 1: Exploring Data", "Readings: Chapters 1-4 in Machine Learning with Python Cookbook")

HTML(value='\n    <div align="center">\n    <h1 style="font-variant:smallcaps; font-family:Times New Roman;">W…

In [7]:
html(2, "Week 1 Discussion/Participation", "What is Pandas and what are some of the most useful Pandas functions?")

HTML(value='\n    <div align="center">\n    <h2 style="font-variant:smallcaps; font-family:Times New Roman;">W…

Pandas is a python module used in data analysis. It is used for data manipulation and the most useful Pandas functions is creating dataframes and can be used to read and write csv files using `pandas.DataFrame()`, `pandas.read_csv()`, and `pandas.to_csv()` (although typically `pandas` is imported using an abbreviation `import pandas as pd` in most textbooks. In my experience working with Pandas, I find it indispensible for data analysis using Python, and more intuitive and versatile than any packages/libraries available in R. The most useful Pandas functions, other than the ones already mentioned, are `pandas.pivot()`, `pandas.melt()`, and `pandas.concat()`, which allow to manipulate different views and merge between datasets.  

**References**

*Pandas API Reference* (2026) Pandas PyData. https://pandas.pydata.org/

In [10]:
html(2, "Week 1 Exercise 1.2: Exploring a Pandas Data Frame")

HTML(value='\n    <div align="center">\n    <h2 style="font-variant:smallcaps; font-family:Times New Roman;">W…

In [153]:
# 1. Load the dataset as a Pandas data frame
import pandas as pd
df = pd.read_csv("./data/video_game_sales.csv", encoding = "utf-8")

In [22]:
# 2. Display the first ten rows of data
ten = df.head(10)
print(ten)

                        Name Platform  Year_of_Release         Genre  \
0                 Wii Sports      Wii           2006.0        Sports
1          Super Mario Bros.      NES           1985.0      Platform
2             Mario Kart Wii      Wii           2008.0        Racing
3          Wii Sports Resort      Wii           2009.0        Sports
4   Pokemon Red/Pokemon Blue       GB           1996.0  Role-Playing
5                     Tetris       GB           1989.0        Puzzle
6      New Super Mario Bros.       DS           2006.0      Platform
7                   Wii Play      Wii           2006.0          Misc
8  New Super Mario Bros. Wii      Wii           2009.0      Platform
9                  Duck Hunt      NES           1984.0       Shooter

  Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  \
0  Nintendo     41.36     28.96      3.77         8.45         82.53
1  Nintendo     29.08      3.58      6.81         0.77         40.24
2  Nintendo     15.68     12.76      3.79         3.29         35.52
3  Nintendo     15.61     10.93      3.28         2.95         32.77
4  Nintendo     11.27      8.89     10.22         1.00         31.37
5  Nintendo     23.20      2.26      4.22         0.58         30.26
6  Nintendo     11.28      9.14      6.50         2.88         29.80
7  Nintendo     13.96      9.18      2.93         2.84         28.92
8  Nintendo     14.44      6.94      4.70         2.24         28.32
9  Nintendo     26.93      0.63      0.28         0.47         28.31

   Critic_Score  Critic_Count User_Score  User_Count Developer Rating
0          76.0          51.0          8       322.0  Nintendo      E
1           NaN           NaN        NaN         NaN       NaN    NaN
2          82.0          73.0        8.3       709.0  Nintendo      E
3          80.0          73.0          8       192.0  Nintendo      E
4           NaN           NaN        NaN         NaN       NaN    NaN
5           NaN           NaN        NaN         NaN       NaN    NaN
6          89.0          65.0        8.5       431.0  Nintendo      E
7          58.0          41.0        6.6       129.0  Nintendo      E
8          87.0          80.0        8.4       594.0  Nintendo      E
9           NaN           NaN        NaN         NaN       NaN    NaN

In [27]:
# 3.1 Find the dimensions (number of rows and columns) in the data frame. 

rows = len(df)
columns = list(df.columns)

html(4, "3.1 Find the dimensions (number of rows and columns) in the data frame. ", "There are 16,719 rows and 16 columns.")
html(4, "3.2 What do these two numbers represent in the context of the data?", "These numbers represent the number of video games and the number of attributes that describe each, respectively.")

HTML(value='\n    <div align="center">\n    <h4 style="font-variant:smallcaps; font-family:Times New Roman;">3…

HTML(value='\n    <div align="center">\n    <h4 style="font-variant:smallcaps; font-family:Times New Roman;">3…

In [92]:
df = df.sort_values(by = "Critic_Score", ascending = False)
df.head(6)
html(4, "4. Find the top five games by critic score", "Tony Hawk's Pro Skater 2, SoulCalibur, Grand Theft Auto IV, Grand Theft Auto V, Super Mario Galaxy")

HTML(value='\n    <div align="center">\n    <h4 style="font-variant:smallcaps; font-family:Times New Roman;">4…

In [93]:
html(4, "5. Find the number of video games in the dataframe in each genre", """Racing = 1249<br>
Simulation = 874<br>
Action = 3370<br>
Platform = 888<br>
Shooter = 1323<br>
Puzzle = 580<br>
Role-Playing = 1500<br>
Strategy = 683<br>
Sports = 2348<br>
Adventure = 1303<br>
Fighting = 849<br>
Misc = 1750<br>""")
genre = df["Genre"]
unique = set(list(genre))

for x in unique:
    df2 = df[df["Genre"] == f"{x}"]
    print(f"{x} = {len(df2)}<br>")

HTML(value='\n    <div align="center">\n    <h4 style="font-variant:smallcaps; font-family:Times New Roman;">5…

Racing = 1249<br>
Simulation = 874<br>
Action = 3370<br>
Platform = 888<br>
Shooter = 1323<br>
Puzzle = 580<br>
Role-Playing = 1500<br>
Strategy = 683<br>
Sports = 2348<br>
Adventure = 1303<br>
Fighting = 849<br>
nan = 0<br>
Misc = 1750<br>

In [94]:
# Find the first five games in the data frame on the SNES platform
columns = ["Platform"]
for x in columns:
    print(set(list(df[x])))

snes = df.loc[df["Platform"] == "SNES", "Name"]
snes.head(5)

html(4, "6. Find the first five games in the data frame on the SNES platform", "Super Mario World, Super Mario All-Stars, Donkey Kong Country, Super Mario Kart, Street Fighter II")

{'TG16', 'XB', 'XOne', 'Wii', 'GEN', 'X360', 'PS4', '3DS', 'PC', 'PS', 'PS2', 'DC', 'PS3', 'PCFX', 'GBA', 'WS', '2600', 'PSP', 'NES', '3DO', 'SNES', 'PSV', 'SAT', 'GC', 'WiiU', 'NG', 'GG', 'GB', 'DS', 'N64', 'SCD'}

HTML(value='\n    <div align="center">\n    <h4 style="font-variant:smallcaps; font-family:Times New Roman;">6…

In [95]:
# Find the five publishers with the highest total global sales. Note: You will need to calculate the total global sales for each publisher.
publishers = set(list(df["Publisher"]))

publisher_global_sales = {}
for x in publishers:
    df2 = df.loc[df["Publisher"] == f"{x}"]
    global_sale = sum(df2["Global_Sales"])
    publisher_global_sales[x] = global_sale

df3 = pd.DataFrame(list(publisher_global_sales.items()))
df3.columns = ["Publisher", "Global_Sales"]
df3 = df3.sort_values(by = "Global_Sales", ascending = False)
df3.head(5)

html(4, "7. Find the five publishers with the highest total global sales. Note: You will need to calculate the total global sales for each publisher.",
     """1. Nintendo (1,788.81 sales)<br>
     2. Electronic Arts (1,116.96 sales)<br>
     3. Activision (731.16 sales)<br>
     4. Sony Computer Entertainment (606.48 sales)<br>
     5. Ubisoft (471.61 sales)""")

HTML(value='\n    <div align="center">\n    <h4 style="font-variant:smallcaps; font-family:Times New Roman;">7…

In [106]:
html(4, "8. Create a new column in the data frame that calculates the percentage of global sales from North America", "")
df["Percent_from_NA (%)"] = round((df["NA_Sales"]/df["Global_Sales"] * 100),2)
df = df.drop(columns = "Percent_NA")
df.head(5)

HTML(value='\n    <div align="center">\n    <h4 style="font-variant:smallcaps; font-family:Times New Roman;">8…

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,Percent_from_NA (%)
57,Grand Theft Auto IV,PS3,2008.0,Action,Take-Two Interactive,4.76,3.69,0.44,1.61,10.50,98.0,64.0,7.5,2833.0,Rockstar North,M,45.33
5350,SoulCalibur,DC,1999.0,Fighting,Namco Bandai Games,0.00,0.00,0.34,0.00,0.34,98.0,24.0,8.8,200.0,Namco,T,0.00
227,Tony Hawk's Pro Skater 2,PS,2000.0,Sports,Activision,3.05,1.41,0.02,0.20,4.68,98.0,19.0,7.7,299.0,Neversoft Entertainment,T,65.17
51,Grand Theft Auto IV,X360,2008.0,Action,Take-Two Interactive,6.76,3.07,0.14,1.03,11.01,98.0,86.0,7.9,2951.0,Rockstar North,M,61.40
165,Grand Theft Auto V,XOne,2014.0,Action,Take-Two Interactive,2.81,2.19,0.00,0.47,5.48,97.0,14.0,7.9,764.0,Rockstar North,M,51.28

In [117]:
html(4, "9. Find the number of NaN (missing values in each column)")

columns = list(df.columns)
df = df.fillna("")
for x in columns:
    nan = df[df[x] == ""]
    print(f"{x} = {len(nan)}")

HTML(value='\n    <div align="center">\n    <h4 style="font-variant:smallcaps; font-family:Times New Roman;">9…

Name = 2
Platform = 0
Year_of_Release = 269
Genre = 2
Publisher = 54
NA_Sales = 0
EU_Sales = 0
JP_Sales = 0
Other_Sales = 0
Global_Sales = 0
Critic_Score = 8582
Critic_Count = 8582
User_Score = 6704
User_Count = 9129
Developer = 6623
Rating = 6769

In [119]:
html(3, "10. Try to calculate the median user score of all video games.")

HTML(value='\n    <div align="center">\n    <h3 style="font-variant:smallcaps; font-family:Times New Roman;">1…

In [147]:
df.head()
user_score = df["User_Score"].dropna()
from statistics import median
median = median(user_score)

html(4, "10.1 Find and replace the numerical string with NaN and then calculate the median", f"Median = {median}")

HTML(value='\n    <div align="center">\n    <h4 style="font-variant:smallcaps; font-family:Times New Roman;">1…

In [155]:
html(4, "10.2 Then replace all NaN entries in the user score column with the median value")
df["User_Score"] = df["User_Score"].fillna(8)
df.head()

HTML(value='\n    <div align="center">\n    <h4 style="font-variant:smallcaps; font-family:Times New Roman;">1…

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,8,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,8,NaN,NaN,NaN